[project]
name = "CORDIAL" # Likely needs to be changed if you want to distribute on PyPI
version = "2025.0.0"
description = "Predicts small molecule - protein interaction affinities using convolutional representations of distance-dependent interactions with attention learning."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
authors = [
    { name = "Benjamin P. Brown", email = "benjamin.p.brown@vanderbilt.edu" },
]
license-file = [ "LICENSE" ]

dependencies = [
    "numpy",
    "pandas",
    "psutil",
    "scipy",
    "torch",
    "scikit-learn",
    "rdkit",
    "biopython",
]

[project.scripts]
cordial = "CORDIAL.main:main"

[project.urls]
source = "https://github.com/bpBrownLab/CORDIAL"
publication = "https://doi.org/10.1073/pnas.2508998122"
homepage = "https://www.bpbrownlab.org/"

# Build settings ----------------------------------------------------------------------
[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
